import { ThemeVariables } from './theme';

export default function ({}: ThemeVariables) {
  return {
    svg: {
      HomeTab: require('./assets/svg/home_tab.svg'),
      HomeSearch: require('./assets/svg/home_search.svg'),
      HeaderSearch: require('./assets/svg/header_search.svg'),
      CreateTab: require('./assets/svg/CreateTab.svg'),
      ActivityTab: require('./assets/svg/ActivityTab.svg'),
      PaymentTab: require('./assets/svg/PaymentTab.svg'),
      CalenderTab: require('./assets/svg/Calender_Tab.svg'),
      Calender: require('./assets/svg/Calender.svg'),
      BookingTab: require('./assets/svg/booking_tab.svg'),
      ProfileTab: require('./assets/svg/ProfileTab.svg'),
      Profile: require('./assets/svg/profile.svg'),
      ChatTab: require('./assets/svg/chat_tab.svg'),
      Catalogue: require('./assets/svg/catalogue_tab.svg'),
      Logout: require('./assets/svg/logout.svg'),
      LogoutBlack: require('./assets/svg/logout-black.svg'),
      Chat: require('./assets/svg/chat.svg'),
      Plus: require('./assets/svg/Plus.svg'),
      ThumbsUp: require('./assets/svg/ThumbsUp.svg'),
      Notification: require('./assets/svg/notification.svg'),
      UserFriends: require('./assets/svg/Friends.svg'),
      MyFriends: require('./assets/svg/friends-my-friends.svg'),
      NotificationTab: require('./assets/svg/Notifications.svg'),
      ArrowRight: require('./assets/svg/arrow_right.svg'),
      BackButton: require('./assets/svg/back_button.svg'),
      BackArrow: require('./assets/svg/back_arrow.svg'),
      Search: require('./assets/svg/search.svg'),
      ArrowDown: require('./assets/svg/arrow_down.svg'),
      EditProfile: require('./assets/svg/edit_profile.svg'),
      Edit: require('./assets/svg/edit.svg'),
      Logo_With_Text: require('./assets/svg/Logo_With_Text.svg'),
      UpDown: require('./assets/svg/UpDown.svg'),
      ImagePlaceholder: require('./assets/svg/ImagePlaceholder.svg'),

      // Settings icons
      SettingAccountInfo: require('./assets/svg/setting_account_info.svg'),
      SettingNotifications: require('./assets/svg/setting_notifications.svg'),
      SettingPrivacySetting: require('./assets/svg/setting_privacy_setting.svg'),
      SettingAppPreferences: require('./assets/svg/setting_app_preferences.svg'),
      SettingHelpSupport: require('./assets/svg/setting_help_support.svg'),
      SettingAbout: require('./assets/svg/setting_about.svg'),
      Users: require('./assets/svg/Users.svg'),
      Like: require('./assets/svg/Like.svg'),
      Comment: require('./assets/svg/Comment.svg'),
      Location: require('./assets/svg/Location.svg'),
      Ticket: require('./assets/svg/Ticket.svg'),
      Eye: require('./assets/svg/Eye.svg'),
    },
    png: {
      Logo: require('./assets/images/Logo.png'),
      EditProfileImg: require('./assets/images/edit-profile-img-1.png'),
      Map: require('./assets/images/map.png'),
      EventDetail: require('./assets/images/event_detail.png'),
    },
  };
}
