const PLUSJAKARTASANS_BOLD = 'PlusJakartaSans-Bold';
const PLUSJAKARTASANS_BOLDITALIC = 'PlusJakartaSans-BoldItalic';
const PLUSJAKARTASANS_EXTRABOLD = 'PlusJakartaSans-ExtraBold';
const PLUSJAKARTASANS_EXTRABOLDITALIC = 'PlusJakartaSans-ExtraBoldItalic';
const PLUSJAKARTASANS_EXTRALIGHT = 'PlusJakartaSans-ExtraLight';
const PLUSJAKARTASANS_EXTRALIGHTITALIC = 'PlusJakartaSans-ExtraLightItalic';
const PLUSJAKARTASANS_ITALIC = 'PlusJakartaSans-Italic';
const PLUSJAKARTASANS_LIGHT = 'PlusJakartaSans-Light';
const PLUSJAKARTASANS_LIGHTITALIC = 'PlusJakartaSans-LightItalic';
const PLUSJAKARTASANS_MEDIUM = 'PlusJakartaSans-Medium';
const PLUSJAKARTASANS_MEDIUMITALIC = 'PlusJakartaSans-MediumItalic';
const PLUSJAKARTASANS_REGULAR = 'PlusJakartaSans-Regular';
const PLUSJAKARTASANS_SEMIBOLD = 'PlusJakartaSans-SemiBold';
const PLUSJAKARTASANS_SEMIBOLDITALIC = 'PlusJakartaSans-SemiBoldItalic';

export default {
  PLUSJAKARTASANS_BOLD,
  PLUSJAKARTASANS_BOLDITALIC,
  PLUSJAKARTASANS_EXTRABOLD,
  PLUSJAKARTASANS_EXTRABOLDITALIC,
  PLUSJAKARTASANS_EXTRALIGHT,
  PLUSJAKARTASANS_EXTRALIGHTITALIC,
  PLUSJAKARTASANS_ITALIC,
  PLUSJAKARTASANS_LIGHT,
  PLUSJAKARTASANS_LIGHTITALIC,
  PLUSJAKARTASANS_MEDIUM,
  PLUSJAKARTASANS_MEDIUMITALIC,
  PLUSJAKARTASANS_REGULAR,
  PLUSJAKARTASANS_SEMIBOLD,
  PLUSJAKARTASANS_SEMIBOLDITALIC,
};
